### PR TITLE
New app icon

### PR DESCRIPTION
**Pull request by rjoonas**
Would you like to use the new Junat.net logo? Does it look any good on Sailfish?

### CODE REVIEW

**Comment by Jollailija** [comment]
Thanks, I'll merge it and see if I can "Sailfish-ify" it a bit.

**Comment by Jollailija** [comment]
There's the first Sailfish-ifying attempt. Will be included in next release (after I fix bookmark bug: https://github.com/Jollailija/junatnet/issues/2) https://github.com/Jollailija/junatnet/commit/6977a4655f45ce8976aed9d887bd65dfe8c49144

**Comment by Jollailija** [comment]
Oh, and by the way: Can I use the [fancy background picture](http://cdn.junat.net/tracks.jpg) of yours as the Jolla Store page background? That would make the Store page a hundread times cooler :stuck_out_tongue:

**Comment by rjoonas** [comment]
Go ahead, it is derived from a public domain original so I can't claim it as mine anyway.

**Pull request merged**
